"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

type ProjectLink = {
  label: string;
  href: string;
};

type Highlight = {
  title: string;
  body: string;
};

type Project = {
  id: string;
  title: string;
  category: string;
  role?: string;
  headline?: string;
  context: string;
  summary: string;
  links: ProjectLink[];
  image?: string;
  highlights?: Highlight[];
  stack?: string;
};

const projects: Project[] = [
  {
    id: "general-translation",
    title: "General Translation",
    category: "internship",
    context: "SWE + growth eng intern · SF summer · 5th employee, 2nd intern",
    role: "devtools + growth",
    headline:
      "Helped ship an AI agent that installs our SDK via GitHub PR, and drove ~300k views on technical content.",
    summary:
      "General Translation is a developer tool for localization \u2014 it translates web apps into other languages. I moved to SF before my freshman year as the 5th employee. I worked on Locadex, an AI agent that implements our library on Next.js codebases by opening a GitHub PR, built the CI/CD actions and dashboard around it, redesigned and shipped the landing page, and ran growth experiments.",
    image: "/projects/general-translation.jpg",
    links: [{ label: "Site", href: "https://generaltranslation.com" }],
    highlights: [
      {
        title: "Landing page redesign",
        body: "Redesigned and coded the whole landing page, iterating with the founder — result got compliments from the board and investors.",
      },
      {
        title: "Locadex testing + eval",
        body: "Testing and eval for Locadex, an AI agent that implements the library — covering edge cases like React fragments and bad async rendering practices.",
      },
      {
        title: "CI/CD actions + dashboard",
        body: "Built CI/CD GitHub Action commands that work with the Locadex agent, and implemented the dashboard side so teams can run and monitor those flows.",
      },
      {
        title: "Growth engineering",
        body: "Built features for virality and gathered ~300k views on technical spaces.",
      },
    ],
    stack: "TypeScript, Next.js, React, GitHub Actions / CI/CD, Python",
  },
  {
    id: "sync",
    title: "Sync",
    category: "full stack",
    context: "HackIllinois · Modal + Solana tracks",
    role: "ml + systems",
    headline:
      "A rhythm game whose levels are generated by an LSTM trained on your top songs, with terrain seeded by on-chain verifiable randomness.",
    summary:
      "Geometry Dash on crack. Most of my team was new to hackathons, so we aimed for something genuinely fun to play and technically ambitious enough to compete. I'd wanted to train a model on MIDI for a while, so we generated the soundtrack from a player's top song and synced the terrain to its beat \u2014 then used Solana VRF so duel opponents can't game the level seed. Practical? Not really. But it was the hardest thing I've built, and the writeup in the README covers why.",
    links: [
      { label: "GitHub", href: "https://github.com/michellee-wang/sync" },
    ],
    highlights: [
      {
        title: "Music Generation",
        body: "Trained an LSTM on Modal GPUs to generate tracks from a user's top song MIDI, then deployed inference as a REST API on Modal so the game client could request levels without running training locally.",
      },
      {
        title: "TypeScript Game Engine",
        body: "Built the full game in TypeScript with custom gravity, collisions, jump arcs, and terrain generation synced to the music beat (Tone.js for audio timing).",
      },
      {
        title: "Verifiable Randomness",
        body: "Used ORAO VRF on Solana so terrain generation is cryptographically verifiable — not just a client-side PRNG that duel opponents could game.",
      },
      {
        title: "Auth + Data",
        body: "Privy for wallet auth (no browser extension required), Firebase for scores and duel match state; wallet connect only when staking or dueling. Solana/Anchor programs handle on-chain stake and duel settlement.",
      },
    ],
    stack:
      "Next.js + React (TypeScript), custom TS game engine, Tone.js, Solana/Anchor, ORAO VRF, Privy, Firebase, Modal-hosted LSTM inference",
  },
  {
    id: "ascend",
    title: "Ascend",
    category: "events",
    context: "Hack Club Athena · hackathon organizer · Jan 2023–Present",
    role: "community + devrel",
    headline:
      "Raised $53,560 and brought 50 students from 6 countries and 27 states to LA for the largest U.S. high school girls' hackathon of 2024.",
    summary:
      "Much of my high school work was with Hack Club, a nonprofit, getting more girls into CS. I organized Ascend and owned every piece of logistics \u2014 venue, food, flights, budget \u2014 plus the coding workshops and mentorship that ran through the weekend. Hack Club gave us full autonomy even though the whole organizing team was in high school.",
    image: "/projects/ascend.png",
    links: [
      { label: "GitHub", href: "https://github.com/hackclub/ascend" },
    ],
    highlights: [
      {
        title: "Ascend logistics",
        body: "Brought 50 students from 6 countries and 27 states to LA to build and ship projects, then pitch them to VCs and SpaceX engineers.",
      },
      {
        title: "Fundraising + budget",
        body: "Raised $53,560 and partnered with SpaceX, Girls Who Code, and Kode with Klossy, and managed the full budget including international travel logistics for attendees who otherwise could not have attended.",
      },
      {
        title: "Blossom",
        body: "Co-Organized Blossom, Atlanta's first gender-focused hackathon, in partnership with Girl Scouts of Atlanta — taught 40 students with no prior programming experience to build and demo their first project.",
      },
    ],
  },
  {
    id: "muse",
    title: "Muse 🎵",
    category: "full stack",
    context:
      "built for an open ended assignment for Northwestern's Disc club · API may be asleep on Render's free tier — first request can take a minute",
    role: "full stack",
    headline:
      "Took a club project off stubbed data and onto real Supabase auth and persisted accounts.",
    summary:
      "Muse matches people by music taste via Spotify \u2014 profiles, top artists, and saved connections. It started as a club project running on a stubbed user API; I migrated auth to Supabase so real accounts and saved connections persist instead of random artist data.",
    links: [
      { label: "Live", href: "https://disc-app-five.vercel.app" },
      { label: "API", href: "https://disc-users-api.onrender.com" },
      { label: "GitHub", href: "https://github.com/michellee-wang/muse" },
    ],
    highlights: [
      {
        title: "Spotify OAuth",
        body: "Spotify OAuth 2.0 + Web API to authenticate users, sync profile data, and display personalized top artists.",
      },
      {
        title: "Social Discovery",
        body: "Browse users by taste, open profiles, and save connections in-app against persisted user records.",
      },
      {
        title: "Auth Migration",
        body: "Replaced stub/random artist flows with Supabase Auth + PostgreSQL so real accounts and saved connections persist across sessions.",
      },
      {
        title: "Backend API",
        body: "RESTful API with 6+ endpoints for auth, connection saving, and Spotify data. Frontend on Vercel, backend on Render — CORS middleware and environment-based config for production cross-origin requests.",
      },
    ],
    stack: "React, Node.js, Express, PostgreSQL, Supabase, Spotify API",
  },
  {
    id: "wharton",
    title: "Basketball Tournament Prediction Analysis",
    category: "data science",
    context: "Wharton Data Science Competition",
    role: "data science",
    headline:
      "78.5% prediction accuracy and 0.86 AUC across 10,438+ NCAA games.",
    summary:
      "Predictive analytics pipeline over 10,438+ NCAA basketball game records \u2014 Elo, WHR, and KenPom team ratings feeding an ensemble of classifiers.",
    links: [
      {
        label: "Competition",
        href: "https://wsb.wharton.upenn.edu/wharton-data-competition/",
      },
      {
        label: "GitHub",
        href: "https://github.com/michellee-wang/wharton-data-sci",
      },
    ],
    highlights: [
      {
        title: "Rating Systems",
        body: "Implemented Elo, Whole-History Rating (WHR), and KenPom algorithms to generate dynamic team strength rankings used as model features.",
      },
      {
        title: "Model Benchmarking",
        body: "Trained and tuned Logistic Regression, Random Forest, and Gradient Boosting with Scikit-learn — 78.5% accuracy and 0.86 AUC via tuning and cross-validation.",
      },
      {
        title: "Ensemble",
        body: "Combined model outputs into an ensemble for more stable tournament predictions than any single classifier alone.",
      },
      {
        title: "Data Pipeline",
        body: "Processed 10,438+ game records — joined game logs, regional groups, and team metadata across CSVs; visualized performance with Matplotlib and Seaborn for the Wharton presentation.",
      },
    ],
    stack:
      "Python, pandas, numpy, scikit-learn, XGBoost, matplotlib, seaborn, Jupyter",
  },
  {
    id: "gtri",
    title: "RF Comms — GTRI",
    category: "research",
    context:
      "Systems Intern · Georgia Tech Research Institute · Sensor & Electromagnetic Applications Lab · June–July 2024",
    role: "research",
    headline:
      "Under 10dB signal loss and 99% transmission efficiency across the 2.4\u20135.8 GHz bands.",
    summary:
      "Under the mentorship of Daniel Martinez in the SEAL Lab, my team designed, prototyped, and validated an RF transmitter/receiver, then documented the test procedures so other researchers could reproduce them.",
    image: "/projects/gtri.png",
    links: [],
    highlights: [
      {
        title: "RF TX/RX design",
        body: "Designed, prototyped, and validated an RF transmitter/receiver with under 10dB signal loss and 99% transmission efficiency across the 2.4–5.8 GHz bands.",
      },
      {
        title: "Lab validation",
        body: "Validated performance with spectrum and network analyzers across 5+ circuit configurations.",
      },
      {
        title: "Documentation + presentation",
        body: "Documented test procedures so other researchers could reproduce them, and presented findings to senior research staff.",
      },
    ],
    stack: "RF circuit design, spectrum analyzer, network analyzer",
  },
];

function ProjectCard({ project }: { project: Project }) {
  const [open, setOpen] = useState(false);
  const hasDetails = !!(project.highlights && project.highlights.length > 0);

  return (
    <article className="relative border border-[color:color-mix(in_srgb,var(--accent-color)_30%,transparent)] bg-[color-mix(in_srgb,var(--accent-color)_5%,transparent)] rounded-2xl overflow-hidden shadow-sm transition-shadow hover:shadow-md">
      <div className="absolute top-3 right-3 z-10 flex flex-wrap justify-end gap-1.5">
        {project.role && (
          <span className="rounded-full bg-[var(--accent-color)] px-2.5 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-white">
            {project.role}
          </span>
        )}
        <span className="rounded-full border border-[color:color-mix(in_srgb,var(--accent-color)_40%,transparent)] bg-white/90 px-2.5 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-[var(--accent-color-darker)]">
          {project.category}
        </span>
      </div>

      <div
        className={`grid ${
          project.image ? "md:grid-cols-[minmax(0,1.1fr)_minmax(0,1.4fr)]" : ""
        }`}
      >
        {project.image && (
          <div className="relative h-44 md:h-full md:min-h-[220px] bg-[#d8e0f2]">
            <Image
              src={project.image}
              alt={`${project.title} preview`}
              fill
              className="object-cover"
              sizes="(max-width: 768px) 100vw, 40vw"
            />
          </div>
        )}

        <div className="p-5 pt-12 md:pt-5">
          <div className="flex items-center gap-2.5 flex-wrap mb-1 md:pr-44">
            <h2 className="text-xl font-bold text-[var(--accent-color-darker)]">{project.title}</h2>
            {project.links.map((link) => (
              <a
                key={link.href}
                href={link.href}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[var(--accent-color)] text-sm font-medium underline underline-offset-2 hover:text-[var(--accent-color-hover)]"
              >
                {link.label}
              </a>
            ))}
          </div>
          <p className="text-xs text-black/55 mb-2">{project.context}</p>
          {project.headline && (
            <p className="text-sm font-semibold text-[var(--accent-color-darker)] leading-relaxed mb-2">
              {project.headline}
            </p>
          )}
          <p className="text-sm text-black/80 leading-relaxed mb-3">
            {project.summary}
          </p>
          {project.stack && (
            <p className="text-xs text-black/55 mb-4 leading-relaxed">
              <span className="font-semibold text-[var(--accent-color-darker)]">STACK: </span>
              {project.stack}
            </p>
          )}

          {hasDetails && (
            <button
              type="button"
              onClick={() => setOpen((v) => !v)}
              aria-expanded={open}
              className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-sm font-medium transition ${
                open
                  ? "border-[color:color-mix(in_srgb,var(--accent-color)_40%,transparent)] text-[var(--accent-color-darker)] bg-white/70 hover:bg-white"
                  : "border-[var(--accent-color)] text-white bg-[var(--accent-color)] hover:bg-[var(--accent-color-hover)]"
              } focus:outline-none focus-visible:ring-2 focus-visible:ring-[color-mix(in_srgb,var(--accent-color)_50%,transparent)] focus-visible:ring-offset-2`}
            >
              {open ? "hide details" : "more details"}
              <svg
                className={`h-3.5 w-3.5 transition-transform duration-200 ${
                  open ? "rotate-180" : ""
                }`}
                viewBox="0 0 16 16"
                fill="none"
                aria-hidden
              >
                <path
                  d="M4 6l4 4 4-4"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </button>
          )}
        </div>
      </div>

      {hasDetails && (
        <div
          className={`grid transition-[grid-template-rows] duration-300 ease-out ${
            open ? "grid-rows-[1fr]" : "grid-rows-[0fr]"
          }`}
        >
          <div className="overflow-hidden">
            <div className="px-5 pb-5 pt-0 border-t border-[color:color-mix(in_srgb,var(--accent-color)_20%,transparent)]">
              <div className="pt-4">
                <h3 className="text-sm font-semibold mb-2 text-[var(--accent-color-darker)] uppercase tracking-wide">
                  Highlights
                </h3>
                <ul className="space-y-2 text-sm">
                  {project.highlights!.map((h) => (
                    <li key={h.title} className="leading-relaxed">
                      <span className="font-semibold text-[var(--accent-color-darker)]">
                        {h.title}.{" "}
                      </span>
                      <span className="text-black/75">{h.body}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      )}
    </article>
  );
}

export default function Projects() {
  return (
    <div className="flex flex-col items-center min-h-screen p-8 bg-gradient-to-b from-[#f7faff] via-white to-white text-black font-krub">
      <main className="max-w-4xl w-full">
        <div className="flex items-center justify-between mb-8">
          <Link
            href="/"
            className="text-[var(--accent-color)] border border-[color:color-mix(in_srgb,var(--accent-color)_40%,transparent)] rounded-full px-3 py-1 hover:bg-[color-mix(in_srgb,var(--accent-color)_10%,transparent)] transition font-medium"
          >
            ← back to home
          </Link>
        </div>

        <h1 className="text-5xl font-bold mb-2 text-[var(--accent-color-dark)]">projects</h1>
        <p className="text-sm mb-8">
          a few things i&apos;ve built recently! full history on{" "}
          <a
            href="https://github.com/michellee-wang"
            target="_blank"
            rel="noopener noreferrer"
            className="underline underline-offset-2 text-[var(--accent-color)] hover:text-[var(--accent-color-hover)]"
          >
            github
          </a>.
        </p>
          <p className="text-sm mb-8">in class i&apos;ve also done{" "}
          <a
            href="https://github.com/michellee-wang/setilab-handout"
            target="_blank"
            rel="noopener noreferrer"
            className="underline underline-offset-2 text-[var(--accent-color)] hover:text-[var(--accent-color-hover)]"
          >
            computer systems labs
          </a>{" "}
          in C &amp; C++ (memory management, low-level systems)
          plus DSA coursework and docker / tooling experience. i&apos;m most comfortable with TypeScript &amp; React, and happiest building at the intersection of web and AI tooling (Claude API, MCP, evals). i learn fast and read docs well, so i&apos;m glad to pick up any new stack.
        </p>

        <div className="grid grid-cols-1 gap-3">
          {projects.map((project) => (
            <ProjectCard key={project.id} project={project} />
          ))}
        </div>
      </main>
    </div>
  );
}
